server:
  port: 8889
spring:
  application:
    name: eureka-client
eureka:
  client:
    service-url:
      defaultZone: http://192.168.137.1:8888/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    status-page-url-path: /info
    #指示eureka服务器在接收到最后一个心跳之后等待的时间（秒），然后才能从此视图中删除此实例，
    #并禁止此实例的流量。
    lease-expiration-duration-in-seconds: 30
    #指示eureka客户端需要向eureka服务器发送心跳以指示它仍然存在的频率（以秒为单位）。
    #如果在leaseExpirationDurationInSeconds中指定的时间段内未收到心跳线，
    #则eureka服务器将从其视图中删除该实例，因此不允许此实例的流量。
    lease-renewal-interval-in-seconds: 5
    health-check-url: /health
